{
    {},
    &isLessEqInts
},
{
    {(void*) 1},
    &isLessEqInts
},
{
    {(void*) 1, (void*) 0},
    &isLessEqInts
},
{
    {(void*) 0, (void*) 1},
    &isLessEqInts
},
{
    {(void*) 2, (void*) 1, (void*) 3},
    &isLessEqInts
},
{
    {
        (void*) 6,
        (void*) 5,
        (void*) 3,
        (void*) 1,
        (void*) 8,
        (void*) 7,
        (void*) 2,
        (void*) 4
    },
    &isLessEqInts
},
